// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgzjrpcooavwgmormqlz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpnempycGNvb2F2d2dtb3JtcWx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwODE2MTAsImV4cCI6MjA2MDY1NzYxMH0.fkblWFOeRi0rQ5J64zE4xCFR4OCnAKshxZ-THaDxCrY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);